namespace Microsoft.Formula.Extensions.CodeGenerator
{
    using System;

    /// <summary>
    /// Defines various constants used in the generator code.
    /// </summary>
    public static class Constants
    {
        public const string GeneratorProperty = "Generator";

        public const string IsThreadSafeProperty = "IsThreadSafe";

        public const string IsObjectGraphProperty = "IsObjectGraph";

        public const string IsNewOnlyProperty = "IsNewOnly";

        /// <summary>The ID of the WPS code generator host.</summary>
        public const string DefaultGeneratorIdString = "4f5a7e3b-98cc-4601-a247-51cdbb9eb444";

        /// <summary>The name of the generator.</summary>
        public const string GeneratorName = "FormulaCodeGenerator";

        /// <summary>The default extension for all files generated by this host.</summary>
        public const string GeneratedFileExtension = ".g.cs";

        /// <summary>The Guid instance for the WPS code generator host.</summary>
        public static readonly Guid DefaultGeneratorId = new Guid(DefaultGeneratorIdString);
    }
}
