//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FormulaParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FormulaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IFormulaParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] FormulaParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.moduleList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleList([NotNull] FormulaParser.ModuleListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] FormulaParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachine([NotNull] FormulaParser.MachineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineBody([NotNull] FormulaParser.MachineBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineSentenceConf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineSentenceConf([NotNull] FormulaParser.MachineSentenceConfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineSentence([NotNull] FormulaParser.MachineSentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineProp([NotNull] FormulaParser.MachinePropContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineSigConfig([NotNull] FormulaParser.MachineSigConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineSig([NotNull] FormulaParser.MachineSigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.machineSigIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineSigIn([NotNull] FormulaParser.MachineSigInContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel([NotNull] FormulaParser.ModelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelBody([NotNull] FormulaParser.ModelBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelSentence([NotNull] FormulaParser.ModelSentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelContractConf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelContractConf([NotNull] FormulaParser.ModelContractConfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelContract([NotNull] FormulaParser.ModelContractContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelFactList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelFactList([NotNull] FormulaParser.ModelFactListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelFact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelFact([NotNull] FormulaParser.ModelFactContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.cardSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCardSpec([NotNull] FormulaParser.CardSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelSigConfig([NotNull] FormulaParser.ModelSigConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelSig([NotNull] FormulaParser.ModelSigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelIntro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelIntro([NotNull] FormulaParser.ModelIntroContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.tSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTSystem([NotNull] FormulaParser.TSystemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.tSystemRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTSystemRest([NotNull] FormulaParser.TSystemRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transSteps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransSteps([NotNull] FormulaParser.TransStepsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transStepConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransStepConfig([NotNull] FormulaParser.TransStepConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransform([NotNull] FormulaParser.TransformContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transformRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransformRest([NotNull] FormulaParser.TransformRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransBody([NotNull] FormulaParser.TransBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transSentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransSentenceConfig([NotNull] FormulaParser.TransSentenceConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransSentence([NotNull] FormulaParser.TransSentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transformSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransformSigConfig([NotNull] FormulaParser.TransformSigConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transformSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransformSig([NotNull] FormulaParser.TransformSigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.transSigIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransSigIn([NotNull] FormulaParser.TransSigInContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomain([NotNull] FormulaParser.DomainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.domSentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomSentences([NotNull] FormulaParser.DomSentencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.domSentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomSentenceConfig([NotNull] FormulaParser.DomSentenceConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.domSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomSentence([NotNull] FormulaParser.DomSentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.domainSigConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomainSigConfig([NotNull] FormulaParser.DomainSigConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.domainSig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomainSig([NotNull] FormulaParser.DomainSigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig([NotNull] FormulaParser.ConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.sentenceConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenceConfig([NotNull] FormulaParser.SentenceConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.settingList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSettingList([NotNull] FormulaParser.SettingListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.setting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetting([NotNull] FormulaParser.SettingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modelParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelParamList([NotNull] FormulaParser.ModelParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.valOrModelParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValOrModelParam([NotNull] FormulaParser.ValOrModelParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.vomParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVomParamList([NotNull] FormulaParser.VomParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.update"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate([NotNull] FormulaParser.UpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep([NotNull] FormulaParser.StepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.choiceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoiceList([NotNull] FormulaParser.ChoiceListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modApply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModApply([NotNull] FormulaParser.ModApplyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModArgList([NotNull] FormulaParser.ModArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modAppArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModAppArg([NotNull] FormulaParser.ModAppArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.stepOrUpdateLHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStepOrUpdateLHS([NotNull] FormulaParser.StepOrUpdateLHSContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modRefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModRefs([NotNull] FormulaParser.ModRefsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModRef([NotNull] FormulaParser.ModRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modRefRename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModRefRename([NotNull] FormulaParser.ModRefRenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.modRefNoRename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModRefNoRename([NotNull] FormulaParser.ModRefNoRenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDecl([NotNull] FormulaParser.TypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.typeDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclBody([NotNull] FormulaParser.TypeDeclBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunDecl([NotNull] FormulaParser.FunDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields([NotNull] FormulaParser.FieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] FormulaParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.mapArrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapArrow([NotNull] FormulaParser.MapArrowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.unnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnnBody([NotNull] FormulaParser.UnnBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.unnCmp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnnCmp([NotNull] FormulaParser.UnnCmpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.typeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeId([NotNull] FormulaParser.TypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.enumList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumList([NotNull] FormulaParser.EnumListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.enumCnst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumCnst([NotNull] FormulaParser.EnumCnstContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.ruleItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleItem([NotNull] FormulaParser.RuleItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.compr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompr([NotNull] FormulaParser.ComprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.comprRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComprRest([NotNull] FormulaParser.ComprRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.bodyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyList([NotNull] FormulaParser.BodyListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] FormulaParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] FormulaParser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.funcTermList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncTermList([NotNull] FormulaParser.FuncTermListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.funcOrCompr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncOrCompr([NotNull] FormulaParser.FuncOrComprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.funcTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncTerm([NotNull] FormulaParser.FuncTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.quoteList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuoteList([NotNull] FormulaParser.QuoteListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.quoteItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuoteItem([NotNull] FormulaParser.QuoteItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] FormulaParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] FormulaParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] FormulaParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnOp([NotNull] FormulaParser.UnOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.binOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinOp([NotNull] FormulaParser.BinOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelOp([NotNull] FormulaParser.RelOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FormulaParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr([NotNull] FormulaParser.StrContext context);
}
